# Dynamic auto-approve rules — generated by eval-housekeeping.js
# DO NOT EDIT MANUALLY — this file is regenerated periodically
# Last updated: 2026-04-01T15:35:54.246Z
#
# These patterns were learned from eval history: commands that were
# consistently approved by AI eval with high confidence.

# Pattern: time
# Learned: 2026-03-01T02:32:03.353Z | Occurrences: 3 | Avg confidence: 95% | Approval rate: 100%
# Example: time curl -s -X POST http://localhost:11436/haiku/api/generate -H 'Content-Type: application/json' -d '{"model":"a
if echo "$NORM_CMD" | grep -qE '^time(\s|$)'; then
    auto_approve
fi

# Pattern: ollama
# Learned: 2026-03-04T21:28:11.099Z | Occurrences: 3 | Avg confidence: 95% | Approval rate: 100%
# Example: ollama list 2>&1
if echo "$NORM_CMD" | grep -qE '^ollama(\s|$)'; then
    auto_approve
fi

# Pattern: truncate
# Learned: 2026-03-05T09:28:11.102Z | Occurrences: 3 | Avg confidence: 95% | Approval rate: 100%
# Example: truncate -s 0 logs/reenrich_phi4_fix.log && PYTHONUNBUFFERED=1 .venv/bin/python -u scripts/reenrich_pipeline_jobs.py 2>&
if echo "$NORM_CMD" | grep -qE '^truncate(\s|$)'; then
    auto_approve
fi

# Pattern: nmap
# Learned: 2026-03-09T11:39:58.095Z | Occurrences: 5 | Avg confidence: 95% | Approval rate: 100%
# Example: nmap -sn 192.168.1.0/24 2>&1 | head -60
if echo "$NORM_CMD" | grep -qE '^nmap(\s|$)'; then
    auto_approve
fi

# Pattern: qemu-system-x86_64
# Learned: 2026-03-09T16:38:05.851Z | Occurrences: 3 | Avg confidence: 95% | Approval rate: 100%
# Example: qemu-system-x86_64 -machine help 2>/dev/null | grep q35 | tail -10
if echo "$NORM_CMD" | grep -qE '^qemu-system-x86_64(\s|$)'; then
    auto_approve
fi

# Pattern: ip
# Learned: 2026-03-10T14:22:10.554Z | Occurrences: 5 | Avg confidence: 95% | Approval rate: 100%
# Example: ip neigh show dev br0 2>&1
if echo "$NORM_CMD" | grep -qE '^ip(\s|$)'; then
    auto_approve
fi

# Pattern: ssh-keyscan
# Learned: 2026-03-23T04:57:03.903Z | Occurrences: 3 | Avg confidence: 95% | Approval rate: 100%
# Example: ssh-keyscan -H my-server 2>/dev/null | head -3
if echo "$NORM_CMD" | grep -qE '^ssh-keyscan(\s|$)'; then
    auto_approve
fi

# Pattern: php
# Learned: 2026-03-23T04:57:03.903Z | Occurrences: 3 | Avg confidence: 95% | Approval rate: 100%
# Example: php -l $HOME/projects/my-site/content.php
if echo "$NORM_CMD" | grep -qE '^php(\s|$)'; then
    auto_approve
fi

# Pattern: export
# Learned: 2026-03-28T03:59:07.572Z | Occurrences: 3 | Avg confidence: 95% | Approval rate: 100%
# Example: export SV_TASK_ID="pro-proxy-debate"
if echo "$NORM_CMD" | grep -qE '^export(\s|$)'; then
    auto_approve
fi

# Pattern: $SSHPASS
# Learned: 2026-04-01T15:35:54.246Z | Occurrences: 3 | Avg confidence: 95% | Approval rate: 100%
# Example: SSHPASS=$HOME/.local/bin/sshpass
$SSHPASS -p 'default' ssh -p 3333 -o StrictHostKeyChecking=no -o UserKnownHostsFi
if echo "$NORM_CMD" | grep -qE '^\$SSHPASS(\s|$)'; then
    auto_approve
fi

# Pattern: +%s);
# Learned: 2026-04-01T15:35:54.246Z | Occurrences: 3 | Avg confidence: 95% | Approval rate: 100%
# Example: START=$(date +%s); sshpass -p default ssh -p 3333 -o StrictHostKeyChecking=no root@localhost "cd /tmp/f5os-triage && pyt
if echo "$NORM_CMD" | grep -qE '^\+%s\);(\s|$)'; then
    auto_approve
fi

# Pattern: 2.1.69
# Learned: 2026-04-01T15:35:54.246Z | Occurrences: 3 | Avg confidence: 95% | Approval rate: 100%
# Example: $HOME/.local/share/claude/versions/2.1.69 open --help 2>&1
if echo "$NORM_CMD" | grep -qE '^2\.1\.69(\s|$)'; then
    auto_approve
fi

# Pattern: "${CLAUDE_PROJECT_DIR:-$(pwd)}")
# Learned: 2026-04-01T15:35:54.246Z | Occurrences: 6 | Avg confidence: 95% | Approval rate: 100%
# Example: project=$(basename "${CLAUDE_PROJECT_DIR:-$(pwd)}") && sv request "Was removing the Ollama-to-Claude AI translation prox
if echo "$NORM_CMD" | grep -qE '^"\$\{CLAUDE_PROJECT_DIR:-\$\(pwd\)\}"\)(\s|$)'; then
    auto_approve
fi

# Pattern: -e
# Learned: 2026-04-01T15:35:54.246Z | Occurrences: 4 | Avg confidence: 95% | Approval rate: 100%
# Example: TOKEN=$(node -e "const {readFileSync}=require('fs'); const c=JSON.parse(readFileSync('$HOME/.claude/.credentials.j
if echo "$NORM_CMD" | grep -qE '^-e(\s|$)'; then
    auto_approve
fi

# Pattern: .git-credentials
# Learned: 2026-04-01T15:35:54.246Z | Occurrences: 5 | Avg confidence: 91% | Approval rate: 100%
# Example: TOKEN=$(cat $HOME/.git-credentials | grep github.com | sed 's|https://.*:\(.*\)@github.com|\1|') && echo "Token le
if echo "$NORM_CMD" | grep -qE '^\.git-credentials(\s|$)'; then
    auto_approve
fi