# Dynamic auto-approve rules — generated by eval-housekeeping.js
# DO NOT EDIT MANUALLY — this file is regenerated periodically
#
# These patterns are learned from eval history: commands that were
# consistently approved by the AI evaluator (95%+ confidence, 100%
# approval rate, 3+ occurrences) are promoted here for zero-latency
# auto-approval.
#
# To regenerate manually: node scripts/eval-housekeeping.js
#
# Last updated: (not yet generated)

# No learned patterns yet. Run the supervisor and the evaluator will
# learn from your approval history over time.
